import React from 'react';

const PrivacyPolicy = () => {
    return ( 
        <div style={{paddingTop:"100px",paddingLeft:"3%",paddingRight:"3%", color:"black"}}>
            <h3 className="mb-2" style={{fontWeight:"bold", color:"black"}}>PRIVACY POLICY</h3>
            <h5 className="mb-4" style={{ color:"black",textAlign:"center"}}>Privacy Polciy (Version 1.0, Effective date: October 13, 2020)</h5>
            <p className="mb-3">This Privacy Policy is a part of and incorporated within and is to be read along with the Terms of Website Use (“Terms”) . The capitalized terms used in this Privacy Policy, but not defined herein, shall have the meaning given to such terms in the Terms.</p>
            <h6 className="mb-2" style={{fontWeight:"bold", color:"black"}}>INFOMATION WE MAY COLLECT FROM YOU</h6>
            <p className="mb-3"><strong>Information you give us : </strong>You may give us information about yourself by filling in forms on the Website or by corresponding with us by phone, e-mail or otherwise. This includes information you provide when you register to use the Website and subscribe to our Services, submit anything for publication on our Website, participate in discussion boards or other social media functions on the Website, enter a competition, promotion or survey and when you report a problem with the Website. The information you give us may include your name, address, e-mail address and phone number. You may also choose to provide other personal information in order to express yourself beyond the required information, such as a short biography, your location, your website, or a picture.Your name, you e-mail id and other information you choose to add to your profile will be available for public viewing on the Website.</p>
            <p className="mb-3"><strong>Information we collect about you : </strong>Information we collect about you. With regard to each of your visits to the Website, we may automatically collect the following information:</p>
            <p className="mb-3">Technical information, including the Internet protocol (IP) address used to connect your computer to the Internet, your login information, browser type and version, time zone setting, browser plug-in types and versions, operating system and platform;</p>
            <p className="mb-3">Information about your visit, including the full Uniform Resource Locators (URL) click stream to, through and from the Website (including date and time); material or information that you viewed or searched for; page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page and any phone number used to call our customer service number.</p>
            <p className="mb-3">If you use your account information with Facebook, Twitter, Google Plus or Gmail or any other social networking or similar site (collectively, “SNS”) to sign in to the Website, an option of which may be provided by the Website to you at its sole discretion, we will collect and store your SNS user ID, and other account information and other information freely made available to the Company by the SNS. The Account Information that is collected includes all the account information provided by you to that website. Please be aware that the other information we obtain from the SNS is often dependent on their privacy policies and/or on your settings regarding what information you have consented to share with services like that of Company’s.</p>
            <p className="mb-3"><strong>Information we receive from other sources : </strong>We may receive information about you if you use any of the other websites we operate or the other services we provide. In this case we will inform you when we collect that data and that it may be shared internally and combined with data collected on this Website. We are also working closely with third parties (including, for example, business partners, sub-contractors in technical, payment and delivery services, advertising networks, analytics providers, search information providers, credit reference agencies) and may receive information about you from such sources. We collect non-personally identifiable information from the Website visitors to track the total of number of visitors to the Website in aggregate form and identify the type of Internet web browser (e.g., Internet Explorer®) and operating system (e.g., Windows®) used by the visitor. This information allows us continuously to improve our Website.</p>
            <p className="mb-3"><strong>Metadata : </strong>Metadata is usually technical data associated with Content you submit, post or share on the Website. Users can add or may have metadata added to their Content including geolocation, date, attribution, or other data.</p>
            <h6 className="mb-2" style={{fontWeight:"bold", color:"black"}}>COOKIES</h6>
            <p className="mb-4">Our Website uses cookies to distinguish you from other users of our Website. This helps us to provide you with a good experience when you browse our Website and also allows us to improve the Website.</p>
            
        </div>
     );
}
 
export default PrivacyPolicy;